'use client';

import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

import { SpssVariableEditor } from './spss-variable-editor';
import type { Question } from '@/types/survey';

interface QuestionSpssFieldsProps {
  question: Question;
  questionId: string;
  questions: Question[];
  formData: Partial<Question>;
  setFormData: React.Dispatch<React.SetStateAction<Partial<Question>>>;
  localExportLabel: string;
  setLocalExportLabel: React.Dispatch<React.SetStateAction<string>>;
  /** 엑셀 라벨 입력 디바운스 타이머 — 부모가 언마운트 시 정리한다. */
  debouncedExportLabelRef: React.MutableRefObject<ReturnType<typeof setTimeout> | null>;
}

/** 질문 편집의 'SPSS 변수명·엑셀 라벨' 구획. 상태는 부모가 그대로 들고 있다. */
export function QuestionSpssFields({
  question,
  questionId,
  questions,
  formData,
  setFormData,
  localExportLabel,
  setLocalExportLabel,
  debouncedExportLabelRef,
}: QuestionSpssFieldsProps) {
  return (
    <>
  {(question?.type !== 'notice' || formData.requiresAcknowledgment) && (
    <div className="rounded-lg border border-gray-200 bg-gray-50 p-4">
      <div className="grid grid-cols-2 gap-4">
        <SpssVariableEditor
          questionCode={formData.questionCode || ''}
          autoGeneratedCode={(() => {
            if (question?.type === 'notice') {
              const notices = questions
                .filter((q) => q.type === 'notice' && q.requiresAcknowledgment)
                .sort((a, b) => a.order - b.order);
              const idx = notices.findIndex((q) => q.id === questionId);
              return `N${idx + 1}`;
            }
            const nonNotice = questions
              .filter((q) => q.type !== 'notice')
              .sort((a, b) => a.order - b.order);
            const idx = nonNotice.findIndex((q) => q.id === questionId);
            return `Q${idx + 1}`;
          })()}
          isCustom={formData.isCustomSpssVarName || false}
          onChangeCode={(code, isCustom) =>
            setFormData((prev) => ({
              ...prev,
              questionCode: code,
              isCustomSpssVarName: isCustom,
            }))
          }
          onReset={() => {
            if (question?.type === 'notice') {
              const notices = questions
                .filter((q) => q.type === 'notice' && q.requiresAcknowledgment)
                .sort((a, b) => a.order - b.order);
              const idx = notices.findIndex((q) => q.id === questionId);
              const autoCode = `N${idx + 1}`;
              setFormData((prev) => ({
                ...prev,
                questionCode: autoCode,
                isCustomSpssVarName: false,
              }));
              return;
            }
            const nonNotice = questions
              .filter((q) => q.type !== 'notice')
              .sort((a, b) => a.order - b.order);
            const idx = nonNotice.findIndex((q) => q.id === questionId);
            const autoCode = `Q${idx + 1}`;
            setFormData((prev) => ({
              ...prev,
              questionCode: autoCode,
              isCustomSpssVarName: false,
            }));
          }}
          options={formData.options?.map((o) => ({
            id: o.id,
            label: o.label,
            value: o.value,
            spssNumericCode: o.spssNumericCode,
          }))}
          allowOtherOption={formData.allowOtherOption}
        />
        <div>
          <Label htmlFor="exportLabel">엑셀 라벨 (선택사항)</Label>
          <Input
            id="exportLabel"
            value={localExportLabel}
            onChange={(e) => {
              const value = e.target.value;
              setLocalExportLabel(value);
              if (debouncedExportLabelRef.current)
                clearTimeout(debouncedExportLabelRef.current);
              debouncedExportLabelRef.current = setTimeout(() => {
                setFormData((prev) => ({ ...prev, exportLabel: value }));
                debouncedExportLabelRef.current = null;
              }, 300);
            }}
            placeholder="예: 성별, TV보유현황"
            className="mt-2"
          />
          <p className="mt-1 text-xs text-gray-500">
            엑셀 헤더에 표시될 라벨 (미입력 시 질문 제목 사용)
          </p>
        </div>
      </div>

      {/* SPSS .sav 변수 타입 / 측정 수준 오버라이드 */}
      <div className="mt-3 grid grid-cols-2 gap-4">
        <div>
          <Label htmlFor="spssVarType">변수 타입</Label>
          <select
            id="spssVarType"
            value={formData.spssVarType || ''}
            onChange={(e) =>
              setFormData((prev) => ({
                ...prev,
                // 빈 값(자동)은 null 로 저장해 DB 오버라이드를 해제한다.
                // select 옵션이 유니온 멤버로 한정되므로 좁히기 단언만 사용.
                spssVarType: (e.target.value || null) as NonNullable<Question['spssVarType']>,
              }))
            }
            className="mt-2 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="">
              자동 (
              {question?.type === 'text' || question?.type === 'textarea'
                ? 'String'
                : question?.type === 'radio' ||
                    question?.type === 'select' ||
                    question?.type === 'checkbox'
                  ? 'Numeric'
                  : 'String'}
              )
            </option>
            <option value="Numeric">Numeric</option>
            <option value="String">String</option>
            <option value="Date">Date</option>
            <option value="DateTime">DateTime</option>
          </select>
        </div>
        <div>
          <Label htmlFor="spssMeasure">측정 수준</Label>
          <select
            id="spssMeasure"
            value={formData.spssMeasure || ''}
            onChange={(e) =>
              setFormData((prev) => ({
                ...prev,
                // 빈 값(자동)은 null 로 저장해 DB 오버라이드를 해제한다.
                spssMeasure: (e.target.value || null) as NonNullable<Question['spssMeasure']>,
              }))
            }
            className="mt-2 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="">자동 (Nominal)</option>
            <option value="Nominal">Nominal (명목형)</option>
            <option value="Ordinal">Ordinal (순서형)</option>
            <option value="Continuous">Continuous (연속형)</option>
          </select>
        </div>
      </div>
    </div>
  )}
    </>
  );
}
