'use client';

import * as React from 'react';
import { RotateCcw } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { validateSpssVarName } from '@/lib/spss/variable-validator';
import { getOtherOptionCode } from '@/utils/option-code-generator';

interface OptionDisplay {
  id: string;
  label: string;
  value: string;
  spssNumericCode?: number | undefined;
}

interface SpssVariableEditorProps {
  questionCode: string;
  autoGeneratedCode: string;
  isCustom: boolean;
  onChangeCode: (code: string, isCustom: boolean) => void;
  onReset: () => void;
  options?: OptionDisplay[] | undefined;
  allowOtherOption?: boolean | undefined;
}

export function SpssVariableEditor({
  questionCode,
  autoGeneratedCode,
  isCustom,
  onChangeCode,
  onReset,
  options,
  allowOtherOption,
}: SpssVariableEditorProps) {
  const displayValue = isCustom ? questionCode : (questionCode || autoGeneratedCode);

  const validationError = React.useMemo(() => {
    if (!isCustom) return null;
    const { valid, errors } = validateSpssVarName(displayValue);
    return valid ? null : (errors[0]?.message ?? null);
  }, [isCustom, displayValue]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    const isModified = newValue !== autoGeneratedCode;
    onChangeCode(newValue, isModified);
  };

  return (
    <div className="space-y-3">
      <div>
        <label className="mb-1 block text-sm font-medium text-gray-700">
          SPSS 변수명
        </label>
        <div className="flex items-center gap-2">
          <Input
            value={displayValue}
            onChange={handleChange}
            placeholder={autoGeneratedCode}
            className="font-mono"
          />
          {isCustom && (
            <Button
              type="button"
              variant="ghost"
              size="icon"
              onClick={onReset}
              title="자동 변수명으로 초기화"
              className="h-9 w-9 shrink-0"
            >
              <RotateCcw className="h-4 w-4" />
            </Button>
          )}
        </div>
        <p className="mt-1 text-xs text-gray-400">
          {isCustom ? `자동: ${autoGeneratedCode}` : '자동 생성됨'}
        </p>
        {validationError && (
          <p className="mt-1 text-xs text-red-600">{validationError}</p>
        )}
      </div>

      {options && options.length > 0 && (
        <div>
          <label className="mb-1 block text-sm font-medium text-gray-700">
            응답값
          </label>
          <div className="space-y-1">
            {options.map((opt) => (
              <div key={opt.id} className="flex items-center gap-2 text-sm">
                <span className="w-8 text-center font-mono font-semibold text-blue-600">
                  {opt.spssNumericCode ?? '—'}
                </span>
                <span className="text-gray-700">{opt.label}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {allowOtherOption && displayValue && (
        <div className="rounded border border-dashed border-amber-300 bg-amber-50 px-3 py-2">
          <p className="text-xs font-medium text-amber-700">
            기타 입력 변수: <span className="font-mono font-semibold">{displayValue}_{getOtherOptionCode(options)}_etc</span>
          </p>
        </div>
      )}
    </div>
  );
}
